name: teabot
description: A tea leaf disease detection app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  tflite_flutter: 0.11.0
  path_provider: ^2.1.1
  flutter_image_compress: ^2.0.3
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_app_check: ^0.2.1+8
  fl_chart: ^0.63.0
  flutter_svg: ^2.0.7
  sqflite: ^2.4.2
  connectivity_plus: ^6.1.4
  path: ^1.8.3
  font_awesome_flutter: ^10.7.0
  image: ^4.1.3
  http: ^1.2.0

dependency_overrides:
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/model.tflite
    - assets/labels.txt
    - assets/tea_logo.svg
    - assets/images/placeholder_leaf.jpg
